1

In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [3]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

U, s, W = np.linalg.svd(A)

V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'A =\n{A}\n')
print(f'U =\n{U}\n')
print(f'D =\n{D}\n')
print(f'V =\n{V}\n')
print(f'Сингулярные числа: {s}')

A =
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

U =
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

D =
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

V =
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]

Сингулярные числа: [8.82 6.14 2.53]


2

In [5]:
norm_evklid = np.max(s)
norm_fro = np.sqrt((s*s).sum())

print(norm_evklid, norm_fro)

print(np.linalg.norm(A, ord=2), np.linalg.norm(A, ord='fro'))

8.824868854820448 11.045361017187265
8.824868854820442 11.045361017187261
